### ISSUE TITLE
Make this lesson language-agnostic

### ISSUE THREAD

**Issue by kcranston** [Reproducible-Science-Curriculum/rr-intro#10]
During the [planning sprint in September 2015](https://github.com/Reproducible-Science-Curriculum/planning/wiki/Curriculum-development-sprint-Sep-2015) we discussed making this lesson language agnostic (or at most, a short R markdown demo that could be substituted with a python example instead).

**Comment by mine-cetinkaya-rundel** [comment]
Intro lesson is now in two parts: 01 is language agnostic, 02 introduces R (and could be substituted with another language version without breaking anything in 01)
