### ISSUE TITLE
Meeting on 4/6 at 4pm to discuss next steps and division of remaining tasks

### ISSUE THREAD

**Issue by mine-cetinkaya-rundel** [Reproducible-Science-Curriculum/rr-intro#4]
mine + @pmagwene + @pschloss + maybe @kristinariemer

goals: 
- finalize the program for the rr-intro sessions
- write the lesson synopsis
- divide up tasks
- set a deadline and (maybe) another meeting to cap off

anything i'm missing?

**Comment by mine-cetinkaya-rundel** [comment]
to do list:
@mine-cetinkaya-rundel 1. turn pre-workshop info to a format that can be shared with participants

@mine-cetinkaya-rundel  2. pick a case study and create an example of instructor's notes

@kristinariemer 3. create a pre-workshop survey asking 
    - ask for swc survey
    - keep it short
    - think about a post component

@pschloss 4. create a reproducibility checklist handout
    - as a separate repo (not sure if we need @hlapp or @kcranston to do this)
    - hand out and discuss after ex 1 during the first session

@pmagwene  5. clean up https://github.com/Reproducible-Science-Curriculum/rr-intro/blob/master/intro-02-instr-notes.Rmd so that the agenda / schedule is clear

deadline: april 20

question for @tracykteal and @hlapp: how do we deliver the materials to the participants? we will have some Rmd files as well as pre-workshop materials (downloading R/RStudio instructions etc.).

**Comment by iamciera** [comment]
Hey all,

@pschloss The checklist was put together by Billy, so it has been started.. I even put a version on [The Guide to Reproducibility website](http://ropensci.github.io/reproducibility-guide/sections/checklist/).  Sorry I cannot find the original markdown though. I will look.

Can you let us know (organization group 1), when you get a better understanding of the concepts the students will learn from the Rstudio lesson?  The students will be doing a lesson in Rstudio in the next section.

**Comment by pschloss** [comment]
Thanks for the suggestion - We were going to split this off into its own
repo. Does that make sense? I think we need a "real" first draft that we
can use to get people's reactions to.

Pat

Sent frim my iPhone, expext more typos then nirmal

On Apr 6, 2015, at 19:42, Ciera Martinez <notifications@github.com> wrote:

Hey all,

@pschloss <https://github.com/pschloss> The checklist was put together by
Billy, so it has been started.. I even put a version on The Guide to
Reproducibility website
<http://ropensci.github.io/reproducibility-guide/sections/checklist/>.
Sorry I cannot find the original markdown though. I will look.

Can you let us know (organization group 1), when you get a better
understanding of the concepts the students will learn from the Rstudio
lesson? The students will be doing a lesson in Rstudio in the next section.

—
Reply to this email directly or view it on GitHub
<https://github.com/Reproducible-Science-Curriculum/rr-intro/issues/4#issuecomment-90285986>
.

**Comment by tracykteal** [comment]
@pschloss in terms of delivering content, do you want the participants to have all the files in the repo, or just some of them? If it's all, then the 'Download zip' github functionality works OK. 

This is a good broader question though. How do we want people to download the files? It would be nice not to have people do it for each module. We could use re-logistics-join to make one repo of all the lessons. @richfitz

**Comment by mine-cetinkaya-rundel** [comment]
@tracykteal We were thinking the participants would get some of the files in the repo for the exercises (only the markdown templates necessary for the exercises). Given that we are to expect some participants new to programming, it might be a bit daunting to have them download the entire repo. We should certainly link to the repo for more info though.

I think it makes sense to have one zipped folder of everything you need for the whole workshop, though I realize this requires some coordination of each group coming up with a list of what those files are for their sessions. Would some sort of tagging of file names help?

**Comment by tracykteal** [comment]
Thanks @mine-cetinkaya-rundel I agree that one delivery of all the necessary files would be best.  

What if in the README there was a 'Files necessary for this lesson' section? Then the files that need to be downloaded could listed, and we can figure out how to get them all together before the workshop. Tagging the files would be good too.

**Comment by mine-cetinkaya-rundel** [comment]
@tracykteal sounds good, we can add such a section to the README

**Comment by tracykteal** [comment]
thanks

Also, did an intro to R and RStudio end up in these lessons? I don't see that it's being covered in other ones, so I wonder if it might need to be here? I can work on that if it's needed.

**Comment by mine-cetinkaya-rundel** [comment]
I believe [this](https://github.com/Reproducible-Science-Curriculum/rr-intro/blob/master/intro-02-instr-notes.Rmd) is what we have for intro to R/RStudio - note that it is work in progress until next week

**Comment by iamciera** [comment]
**File Distribution**: Just keep me updated on how you want the files and I will format properly.

**R Studio** : We introduce them to literate programming and knitting documents in R Studio.  Basically I have a [report ](https://github.com/Reproducible-Science-Curriculum/rr-organization1/blob/master/files/03-literate-programming-activity/countryPick4.rmd) (in progress) where they specify which countries they are interested in at the beginning of the code and the report knits plots those countries. What you have planned should work for R studio introduction to prepare them for our lesson.  They just need to replace four words and run chunks.

Are we just requiring them to come to class with R Studio installed on their computer?

**Comment by KristinaRiemer** [comment]
@iamciera They're supposed to install R and RStudio ahead of time. It's also specified that they can get help with installation during the coffee break at the end of session 1, see instructor notes for that.
