### ISSUE TITLE
Clarify use of and source for Gapminder data

### ISSUE THREAD

**Issue by hlapp** [Reproducible-Science-Curriculum/rr-intro#7]
Organization1 uses the Gapminder data within R, possibly via @jennybc's [gapminder](http://github.com/jennybc/gapminder) package. (@iamciera - can you confirm what the plan is re: where the data will come from?) I thought the Intro lesson does, too, but am not sure, nor whether that would be within RStudio (and hence R) or outside. (@mine-cetinkaya-rundel - can you confirm?) If within R, could perhaps also be installed from CRAN package?

**Comment by iamciera** [comment]
We have in our readme:

- Gapminder data [available here](http://www.gapminder.org/data/). [Gapminder data is licensed CC-BY 3.0](https://docs.google.com/document/pub?id=1POd-pBMc5vDXAmxrpGjPLaCSDSWuxX6FLQgq5DhlUhM#h.ul2gu2-uwathz).
- Processed data via [@jennybc](https://github.com/jennybc), [R package available here](https://github.com/jennybc/gapminder). The [data-raw](https://github.com/jennybc/gapminder/tree/master/data-raw) sub-directory reveals the journey from Gapminder.org's Excel workbooks to increasingly clean and tidy data.
    - cleanest data is in [07_gap-every-five-years.tsv](https://github.com/jennybc/gapminder/blob/master/data-raw/07_gap-every-five-years.tsv)
    - this gives rise to the data.frame provided by the R package

We [were discussing what to do with the datafile](https://github.com/Reproducible-Science-Curriculum/rr-organization1/issues/3) and as of now, it is in the root folder where the markdown report is.   We could use the package, but the students should be aware of how to input files, as their data will most likely not have a package. It would be easier to just install from CRAN though....

**Comment by hlapp** [comment]
If they install the files from a zip file, then the data file would hopefully be in place already, so hopefully this would not be difficult.

However, if they install the package, it's not a bad opportunity to show how one can publish a dataset with all stages of cleaning and massaging documented, and once installed they can use R to find out where the data file is:

```R
gap_tsv <- system.file("gapminder.tsv", package = "gapminder")
```

**Comment by jennybc** [comment]
I was about to add what @hlapp already did: yes you could enjoy the convenience of installing from CRAN but then use `system.file()` to access a `.tsv`. Perhaps even copy it into the local directory, then load explicitly via `read.delim()`, just to make sure they are seeing this process.

**Comment by mine-cetinkaya-rundel** [comment]
@hlapp in the intro lesson they will be provided a csv file with the gapminder data, so that they can first use it with their existing tools as well

**Comment by tracykteal** [comment]
I was just putting together the zip files and a web site, but @dleehr did it already! https://github.com/Reproducible-Science-Curriculum/2015-05-14-duke-materials

Thanks @dleehr! Do folks want to check to make sure everything that's needed is there?

**Comment by dleehr** [comment]
@tracykteal you're welcome! I'm working with the instructors to make materials available upon request, and will be managing it throughout the workshop

**Comment by tracykteal** [comment]
@dleehr awesome, that's great!

**Comment by mine-cetinkaya-rundel** [comment]
added data attribution to rr-intro readme as well
